
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DRDrops :  Luban.EditorBeanBase 
{
    public DRDrops()
    {
            Items = System.Array.Empty<int[]>();
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Items"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } int _n0 = _fieldJson.Count; Items = new int[_n0][]; int _index0=0; foreach(JSONNode __e0 in _fieldJson.Children) { int[] __v0;  if(!__e0.IsArray) { throw new SerializationException(); } int _n1 = __e0.Count; __v0 = new int[_n1]; int _index1=0; foreach(JSONNode __e1 in __e0.Children) { int __v1;  if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1;  __v0[_index1++] = __v1; }    Items[_index0++] = __v0; }  
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {

            if (Items == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Items"] = __cjson0; foreach(var _e0 in Items) { JSONNode __v0; { var __cjson1 = new JSONArray(); __v0 = __cjson1; foreach(var _e1 in _e0) { JSONNode __v1; __v1 = new JSONNumber(_e1); __cjson1.Add(__v1); } } __cjson0.Add(__v0); } }
        }
    }

    public static DRDrops LoadJsonDRDrops(JSONNode _json)
    {
        DRDrops obj = new DRDrops();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRDrops(DRDrops _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    public int Id;

    /// <summary>
    /// 掉落 
    /// </summary>
    public int[][] Items;

}
}

