
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DRGameConfig :  Luban.EditorBeanBase 
{
    public DRGameConfig()
    {
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Scene_Menu"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  SceneMenu = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Scene_Main"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  SceneMain = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Scene_Map2d"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  SceneMap2d = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Scene_MapFight"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  SceneMapFight = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Scene_Menu"] = new JSONNumber(SceneMenu);
        }
        {
            _json["Scene_Main"] = new JSONNumber(SceneMain);
        }
        {
            _json["Scene_Map2d"] = new JSONNumber(SceneMap2d);
        }
        {
            _json["Scene_MapFight"] = new JSONNumber(SceneMapFight);
        }
    }

    public static DRGameConfig LoadJsonDRGameConfig(SimpleJSON.JSONNode _json)
    {
        DRGameConfig obj = new DRGameConfig();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRGameConfig(DRGameConfig _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public int SceneMenu;

    public int SceneMain;

    public int SceneMap2d;

    public int SceneMapFight;

}
}

