
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DRItems :  Luban.EditorBeanBase 
{
    public DRItems()
    {
            AreaName = "";
            Desc = "";
            Attr = new System.Collections.Generic.Dictionary<int,long>();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["ItemType"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  ItemType = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Level"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Level = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Diamond"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Diamond = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["AreaName"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  AreaName = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Desc"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  Desc = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Attr"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } Attr = new System.Collections.Generic.Dictionary<int, long>(); foreach(JSONNode __e0 in _fieldJson.Children) { int __k0;  if(!__e0[0].IsNumber) { throw new SerializationException(); }  __k0 = __e0[0]; long __v0;  if(!__e0[1].IsNumber) { throw new SerializationException(); }  __v0 = __e0[1];  Attr.Add(__k0, __v0); }  
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["ItemType"] = new JSONNumber(ItemType);
        }
        {
            _json["Level"] = new JSONNumber(Level);
        }
        {
            _json["Diamond"] = new JSONNumber(Diamond);
        }
        {

            if (AreaName == null) { throw new System.ArgumentNullException(); }
            _json["AreaName"] = new JSONString(AreaName);
        }
        {

            if (Desc == null) { throw new System.ArgumentNullException(); }
            _json["Desc"] = new JSONString(Desc);
        }
        {

            if (Attr == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Attr"] = __cjson0; foreach(var _e0 in Attr) { var __entry0 = new JSONArray(); __cjson0.Add(__entry0); JSONNode __k0; __k0 = new JSONNumber(_e0.Key); __entry0.Add(__k0); JSONNode __v0; __v0 = new JSONNumber(_e0.Value); __entry0.Add(__v0); }  }
        }
    }

    public static DRItems LoadJsonDRItems(SimpleJSON.JSONNode _json)
    {
        DRItems obj = new DRItems();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRItems(DRItems _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public int Id;

    /// <summary>
    /// 类型
    /// </summary>
    public int ItemType;

    /// <summary>
    /// 品阶
    /// </summary>
    public int Level;

    /// <summary>
    /// 价值
    /// </summary>
    public int Diamond;

    /// <summary>
    /// 生长区域
    /// </summary>
    public string AreaName;

    /// <summary>
    /// 描述
    /// </summary>
    public string Desc;

    /// <summary>
    /// 属性
    /// </summary>
    public System.Collections.Generic.Dictionary<int, long> Attr;

}
}

