
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class DRStages :  Luban.EditorBeanBase 
{
    public DRStages()
    {
            Monsters = System.Array.Empty<int>();
    }

    public override void LoadJson(SimpleJSON.JSONObject _json)
    {
        { 
            var _fieldJson = _json["Id"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Id = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Level"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  Level = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["SubLevel"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  SubLevel = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["Monsters"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsArray) { throw new SerializationException(); } int _n0 = _fieldJson.Count; Monsters = new int[_n0]; int _index0=0; foreach(SimpleJSON.JSONNode __e0 in _fieldJson.Children) { int __v0;  if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0;  Monsters[_index0++] = __v0; }  
            }
        }
        
    }

    public override void SaveJson(SimpleJSON.JSONObject _json)
    {
        {
            _json["Id"] = new JSONNumber(Id);
        }
        {
            _json["Level"] = new JSONNumber(Level);
        }
        {
            _json["SubLevel"] = new JSONNumber(SubLevel);
        }
        {

            if (Monsters == null) { throw new System.ArgumentNullException(); }
            { var __cjson0 = new JSONArray(); _json["Monsters"] = __cjson0; foreach(var _e0 in Monsters) { JSONNode __v0; __v0 = new JSONNumber(_e0); __cjson0.Add(__v0); } }
        }
    }

    public static DRStages LoadJsonDRStages(SimpleJSON.JSONNode _json)
    {
        DRStages obj = new DRStages();
        obj.LoadJson((SimpleJSON.JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonDRStages(DRStages _obj, SimpleJSON.JSONNode _json)
    {
        _obj.SaveJson((SimpleJSON.JSONObject)_json);
    }

    public int Id;

    /// <summary>
    /// 关卡
    /// </summary>
    public int Level;

    /// <summary>
    /// 关卡
    /// </summary>
    public int SubLevel;

    /// <summary>
    /// 怪物
    /// </summary>
    public int[] Monsters;

}
}

