
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class NodeJson :  Luban.EditorBeanBase 
{
    public NodeJson()
    {
            content = "";
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["nodeType"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  nodeType = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["content"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsString) { throw new SerializationException(); }  content = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["nodeType"] = new JSONNumber(nodeType);
        }
        {

            if (content == null) { throw new System.ArgumentNullException(); }
            _json["content"] = new JSONString(content);
        }
    }

    public static NodeJson LoadJsonNodeJson(JSONNode _json)
    {
        NodeJson obj = new NodeJson();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonNodeJson(NodeJson _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    public int nodeType;

    public string content;

}
}

