
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban.SimpleJSON;
using Luban;

namespace ET.Editor
{

public sealed class Vector2Int :  Luban.EditorBeanBase 
{
    public Vector2Int()
    {
    }

    public override void LoadJson(JSONObject _json)
    {
        { 
            var _fieldJson = _json["x"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  x = _fieldJson;
            }
        }
        
        { 
            var _fieldJson = _json["y"];
            if (_fieldJson != null)
            {
                if(!_fieldJson.IsNumber) { throw new SerializationException(); }  y = _fieldJson;
            }
        }
        
    }

    public override void SaveJson(JSONObject _json)
    {
        {
            _json["x"] = new JSONNumber(x);
        }
        {
            _json["y"] = new JSONNumber(y);
        }
    }

    public static Vector2Int LoadJsonVector2Int(JSONNode _json)
    {
        Vector2Int obj = new Vector2Int();
        obj.LoadJson((JSONObject)_json);
        return obj;
    }
        
    public static void SaveJsonVector2Int(Vector2Int _obj, JSONNode _json)
    {
        _obj.SaveJson((JSONObject)_json);
    }

    public int x;

    public int y;

}
}

