
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET.Editor
{
    /// <summary>
    /// Five element root flags
    /// </summary>
    [System.Flags]
    public enum XRoot
    {
        /// <summary>
        /// Gold
        /// </summary>
        Gold = 1,
        /// <summary>
        /// Wood
        /// </summary>
        Wood = 2,
        /// <summary>
        /// Water
        /// </summary>
        Water = 4,
        /// <summary>
        /// Fire
        /// </summary>
        Fire = 8,
        /// <summary>
        /// Ground
        /// </summary>
        Ground = 16,
    }

    public static class XRoot_Metadata
    {
        public static readonly Luban.EditorEnumItemInfo Gold = new Luban.EditorEnumItemInfo("Gold", "", 1, "Gold");
        public static readonly Luban.EditorEnumItemInfo Wood = new Luban.EditorEnumItemInfo("Wood", "", 2, "Wood");
        public static readonly Luban.EditorEnumItemInfo Water = new Luban.EditorEnumItemInfo("Water", "", 4, "Water");
        public static readonly Luban.EditorEnumItemInfo Fire = new Luban.EditorEnumItemInfo("Fire", "", 8, "Fire");
        public static readonly Luban.EditorEnumItemInfo Ground = new Luban.EditorEnumItemInfo("Ground", "", 16, "Ground");

        private static readonly System.Collections.Generic.List<Luban.EditorEnumItemInfo> __items = new System.Collections.Generic.List<Luban.EditorEnumItemInfo>
        {
            Gold,
            Wood,
            Water,
            Fire,
            Ground,
        };

        public static System.Collections.Generic.List<Luban.EditorEnumItemInfo> GetItems() => __items;

        public static Luban.EditorEnumItemInfo GetByName(string name)
        {
            return __items.Find(c => c.Name == name);
        }

        public static Luban.EditorEnumItemInfo GetByNameOrAlias(string name)
        {
            return __items.Find(c => c.Name == name || c.Alias == name);
        }

        public static Luban.EditorEnumItemInfo GetByValue(int value)
        {
            return __items.Find(c => c.Value == value);
        }
    }

} 

