// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormFight
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIWidgetBtmBar m_BtmBarBtmBar;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_CenterRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_NextExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_PreExButton;


        public ET.Client.MonoUIWidgetBtmBar BtmBarBtmBar => m_BtmBarBtmBar;
        public UnityEngine.RectTransform CenterRectTransform => m_CenterRectTransform;
        public Game.ExButton NextExButton => m_NextExButton;
        public Game.ExButton PreExButton => m_PreExButton;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_BtmBarBtmBar == null) return true;
            if (this.m_CenterRectTransform == null) return true;
            if (this.m_NextExButton == null) return true;
            if (this.m_PreExButton == null) return true;
            return false;
        }
#endif
    }
}
