// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormFight
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_L0RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_L1RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_L2RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_L3RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_R0RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_R1RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_R2RectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_R3RectTransform;


        public UnityEngine.RectTransform L0RectTransform => m_L0RectTransform;
        public UnityEngine.RectTransform L1RectTransform => m_L1RectTransform;
        public UnityEngine.RectTransform L2RectTransform => m_L2RectTransform;
        public UnityEngine.RectTransform L3RectTransform => m_L3RectTransform;
        public UnityEngine.RectTransform R0RectTransform => m_R0RectTransform;
        public UnityEngine.RectTransform R1RectTransform => m_R1RectTransform;
        public UnityEngine.RectTransform R2RectTransform => m_R2RectTransform;
        public UnityEngine.RectTransform R3RectTransform => m_R3RectTransform;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_L0RectTransform == null) return true;
            if (this.m_L1RectTransform == null) return true;
            if (this.m_L2RectTransform == null) return true;
            if (this.m_L3RectTransform == null) return true;
            if (this.m_R0RectTransform == null) return true;
            if (this.m_R1RectTransform == null) return true;
            if (this.m_R2RectTransform == null) return true;
            if (this.m_R3RectTransform == null) return true;
            return false;
        }
#endif
    }
}
