// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIWidgetTopBar
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_AgeUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_AgeNameUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_LevelUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_StoneCountUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_StoneNameUXTextMeshPro;


        public UnityEngine.UI.UXTextMeshPro AgeUXTextMeshPro => m_AgeUXTextMeshPro;
        public UnityEngine.UI.UXTextMeshPro AgeNameUXTextMeshPro => m_AgeNameUXTextMeshPro;
        public UnityEngine.UI.UXTextMeshPro LevelUXTextMeshPro => m_LevelUXTextMeshPro;
        public UnityEngine.UI.UXTextMeshPro StoneCountUXTextMeshPro => m_StoneCountUXTextMeshPro;
        public UnityEngine.UI.UXTextMeshPro StoneNameUXTextMeshPro => m_StoneNameUXTextMeshPro;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_AgeUXTextMeshPro == null) return true;
            if (this.m_AgeNameUXTextMeshPro == null) return true;
            if (this.m_LevelUXTextMeshPro == null) return true;
            if (this.m_StoneCountUXTextMeshPro == null) return true;
            if (this.m_StoneNameUXTextMeshPro == null) return true;
            return false;
        }
#endif
    }
}
