// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormBag1
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_CenterRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExLoopVerticalScrollRect m_Grid0LoopVerticalScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExLoopVerticalScrollRect m_Grid1LoopVerticalScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_ItemTemp0ExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_ItemTemp0Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_ItemTemp1ExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_ItemTemp1Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_RetunExButton;

        public UnityEngine.RectTransform CenterRectTransform => this.m_CenterRectTransform;
        public Game.ExLoopVerticalScrollRect Grid0LoopVerticalScrollRect => this.m_Grid0LoopVerticalScrollRect;
        public Game.ExLoopVerticalScrollRect Grid1LoopVerticalScrollRect => this.m_Grid1LoopVerticalScrollRect;
        public Game.ExButton ItemTemp0ExButton => this.m_ItemTemp0ExButton;
        public UnityEngine.UI.Image ItemTemp0Image => this.m_ItemTemp0Image;
        public Game.ExButton ItemTemp1ExButton => this.m_ItemTemp1ExButton;
        public UnityEngine.UI.Image ItemTemp1Image => this.m_ItemTemp1Image;
        public Game.ExButton RetunExButton => this.m_RetunExButton;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_CenterRectTransform == null) return true;
            if (this.m_Grid0LoopVerticalScrollRect == null) return true;
            if (this.m_Grid1LoopVerticalScrollRect == null) return true;
            if (this.m_ItemTemp0ExButton == null) return true;
            if (this.m_ItemTemp0Image == null) return true;
            if (this.m_ItemTemp1ExButton == null) return true;
            if (this.m_ItemTemp1Image == null) return true;
            if (this.m_RetunExButton == null) return true;
            return false;
        }
#endif

    }
}
