// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormBag1
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_CenterRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.CommonLoopScrollRect m_Grid0CommonLoopScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.CommonLoopScrollRect m_Grid1CommonLoopScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_RetunExButton;


        public UnityEngine.RectTransform CenterRectTransform => m_CenterRectTransform;
        public Game.CommonLoopScrollRect Grid0CommonLoopScrollRect => m_Grid0CommonLoopScrollRect;
        public Game.CommonLoopScrollRect Grid1CommonLoopScrollRect => m_Grid1CommonLoopScrollRect;
        public Game.ExButton RetunExButton => m_RetunExButton;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_CenterRectTransform == null) return true;
            if (this.m_Grid0CommonLoopScrollRect == null) return true;
            if (this.m_Grid1CommonLoopScrollRect == null) return true;
            if (this.m_RetunExButton == null) return true;
            return false;
        }
#endif
    }
}
