// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormUnitAttribute
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_MonsterCategoryTemplateTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIUnitAttributeRow m_MonsterItemTemplateAttributeRowTemplate;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_MonsterPanelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_MonsterRowsRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_MonsterTagsTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_MonsterTitleTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_PlayerCategoryTemplateTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIUnitAttributeRow m_PlayerItemTemplateAttributeRowTemplate;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_PlayerPanelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_PlayerRowsRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_PlayerTagsTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_PlayerTitleTextMeshProUGUI;


        public TMPro.TextMeshProUGUI MonsterCategoryTemplateTextMeshProUGUI => m_MonsterCategoryTemplateTextMeshProUGUI;
        public ET.Client.MonoUIUnitAttributeRow MonsterItemTemplateAttributeRowTemplate => m_MonsterItemTemplateAttributeRowTemplate;
        public UnityEngine.RectTransform MonsterPanelRectTransform => m_MonsterPanelRectTransform;
        public UnityEngine.RectTransform MonsterRowsRectTransform => m_MonsterRowsRectTransform;
        public TMPro.TextMeshProUGUI MonsterTagsTextMeshProUGUI => m_MonsterTagsTextMeshProUGUI;
        public TMPro.TextMeshProUGUI MonsterTitleTextMeshProUGUI => m_MonsterTitleTextMeshProUGUI;
        public TMPro.TextMeshProUGUI PlayerCategoryTemplateTextMeshProUGUI => m_PlayerCategoryTemplateTextMeshProUGUI;
        public ET.Client.MonoUIUnitAttributeRow PlayerItemTemplateAttributeRowTemplate => m_PlayerItemTemplateAttributeRowTemplate;
        public UnityEngine.RectTransform PlayerPanelRectTransform => m_PlayerPanelRectTransform;
        public UnityEngine.RectTransform PlayerRowsRectTransform => m_PlayerRowsRectTransform;
        public TMPro.TextMeshProUGUI PlayerTagsTextMeshProUGUI => m_PlayerTagsTextMeshProUGUI;
        public TMPro.TextMeshProUGUI PlayerTitleTextMeshProUGUI => m_PlayerTitleTextMeshProUGUI;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_MonsterCategoryTemplateTextMeshProUGUI == null) return true;
            if (this.m_MonsterItemTemplateAttributeRowTemplate == null) return true;
            if (this.m_MonsterPanelRectTransform == null) return true;
            if (this.m_MonsterRowsRectTransform == null) return true;
            if (this.m_MonsterTagsTextMeshProUGUI == null) return true;
            if (this.m_MonsterTitleTextMeshProUGUI == null) return true;
            if (this.m_PlayerCategoryTemplateTextMeshProUGUI == null) return true;
            if (this.m_PlayerItemTemplateAttributeRowTemplate == null) return true;
            if (this.m_PlayerPanelRectTransform == null) return true;
            if (this.m_PlayerRowsRectTransform == null) return true;
            if (this.m_PlayerTagsTextMeshProUGUI == null) return true;
            if (this.m_PlayerTitleTextMeshProUGUI == null) return true;
            return false;
        }
#endif
    }
}
