// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormUnitAttribute
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_MonsterCategoryTemplateText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIUnitAttributeRow m_MonsterItemTemplateAttributeRowTemplate;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_MonsterPanelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_MonsterRowsRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_MonsterTagsText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_MonsterTitleText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_PlayerCategoryTemplateText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIUnitAttributeRow m_PlayerItemTemplateAttributeRowTemplate;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_PlayerPanelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_PlayerRowsRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_PlayerTagsText;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Text m_PlayerTitleText;


        public UnityEngine.UI.Text MonsterCategoryTemplateText => m_MonsterCategoryTemplateText;
        public ET.Client.MonoUIUnitAttributeRow MonsterItemTemplateAttributeRowTemplate => m_MonsterItemTemplateAttributeRowTemplate;
        public UnityEngine.RectTransform MonsterPanelRectTransform => m_MonsterPanelRectTransform;
        public UnityEngine.RectTransform MonsterRowsRectTransform => m_MonsterRowsRectTransform;
        public UnityEngine.UI.Text MonsterTagsText => m_MonsterTagsText;
        public UnityEngine.UI.Text MonsterTitleText => m_MonsterTitleText;
        public UnityEngine.UI.Text PlayerCategoryTemplateText => m_PlayerCategoryTemplateText;
        public ET.Client.MonoUIUnitAttributeRow PlayerItemTemplateAttributeRowTemplate => m_PlayerItemTemplateAttributeRowTemplate;
        public UnityEngine.RectTransform PlayerPanelRectTransform => m_PlayerPanelRectTransform;
        public UnityEngine.RectTransform PlayerRowsRectTransform => m_PlayerRowsRectTransform;
        public UnityEngine.UI.Text PlayerTagsText => m_PlayerTagsText;
        public UnityEngine.UI.Text PlayerTitleText => m_PlayerTitleText;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_MonsterCategoryTemplateText == null) return true;
            if (this.m_MonsterItemTemplateAttributeRowTemplate == null) return true;
            if (this.m_MonsterPanelRectTransform == null) return true;
            if (this.m_MonsterRowsRectTransform == null) return true;
            if (this.m_MonsterTagsText == null) return true;
            if (this.m_MonsterTitleText == null) return true;
            if (this.m_PlayerCategoryTemplateText == null) return true;
            if (this.m_PlayerItemTemplateAttributeRowTemplate == null) return true;
            if (this.m_PlayerPanelRectTransform == null) return true;
            if (this.m_PlayerRowsRectTransform == null) return true;
            if (this.m_PlayerTagsText == null) return true;
            if (this.m_PlayerTitleText == null) return true;
            return false;
        }
#endif
    }
}
