// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormSkill
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUISkillItem m_ItemTemplateSkillItemTemplate;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_PanelRectTransform;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Button m_ReloadSceneButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.GridLayoutGroup m_SkillGridGridLayoutGroup;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.RectTransform m_SkillGridRectTransform;


        public ET.Client.MonoUISkillItem ItemTemplateSkillItemTemplate => m_ItemTemplateSkillItemTemplate;
        public UnityEngine.RectTransform PanelRectTransform => m_PanelRectTransform;
        public UnityEngine.UI.Button ReloadSceneButton => m_ReloadSceneButton;
        public UnityEngine.UI.GridLayoutGroup SkillGridGridLayoutGroup => m_SkillGridGridLayoutGroup;
        public UnityEngine.RectTransform SkillGridRectTransform => m_SkillGridRectTransform;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_ItemTemplateSkillItemTemplate == null) return true;
            if (this.m_PanelRectTransform == null) return true;
            if (this.m_ReloadSceneButton == null) return true;
            if (this.m_SkillGridGridLayoutGroup == null) return true;
            if (this.m_SkillGridRectTransform == null) return true;
            return false;
        }
#endif
    }
}
