// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoGFEntityHeadItem
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.SpriteRenderer m_FrameSpriteRenderer;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.SpriteRenderer m_HeadSpriteRenderer;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Animation m_RootAnimation;


        public UnityEngine.SpriteRenderer FrameSpriteRenderer => m_FrameSpriteRenderer;
        public UnityEngine.SpriteRenderer HeadSpriteRenderer => m_HeadSpriteRenderer;
        public UnityEngine.Animation RootAnimation => m_RootAnimation;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_FrameSpriteRenderer == null) return true;
            if (this.m_HeadSpriteRenderer == null) return true;
            if (this.m_RootAnimation == null) return true;
            return false;
        }
#endif
    }
}
