
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRBattleCardConfig : Luban.BeanBase
{
    public DRBattleCardConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        SkillCardRuleId = _buf.ReadInt();
        SkillCardRuleId_Ref = null;
        {int __n0 = _buf.ReadSize(); RelicIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); RelicIds[__index0] = __e0;}}
        Desc = _buf.ReadString();
        PostInit();
    }

    public static DRBattleCardConfig DeserializeDRBattleCardConfig(ByteBuf _buf)
    {
        return new DRBattleCardConfig(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// SkillCardRuleId
    /// </summary>
    public readonly int SkillCardRuleId;
    public DRSkillCardRule SkillCardRuleId_Ref { private set; get; }
    /// <summary>
    /// RelicIds
    /// </summary>
    public readonly int[] RelicIds;
    public DRRelic[] RelicIds_Ref { private set; get; }
    /// <summary>
    /// Desc
    /// </summary>
    public readonly string Desc;
    public const int __ID__ = 737310200;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SkillCardRuleId_Ref = tables.DTSkillCardRule.GetOrDefault(SkillCardRuleId);
        RelicIds_Ref = new DRRelic[RelicIds.Length];
        for (int _i = 0; _i < RelicIds.Length; _i++) { RelicIds_Ref[_i] = tables.DTRelic.GetOrDefault(RelicIds[_i]); }

        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "SkillCardRuleId:" + SkillCardRuleId + ","
        + "RelicIds:" + Luban.StringUtil.CollectionToString(RelicIds) + ","
        + "Desc:" + Desc + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
