
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRDrops : Luban.BeanBase
{
    public DRDrops(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int __n0 = _buf.ReadSize(); Items = new int[__n0][];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int[] __e0;{int __n1 = _buf.ReadSize(); __e0 = new int[__n1];for(var __index1 = 0 ; __index1 < __n1 ; __index1++) { int __e1;__e1 = _buf.ReadInt(); __e0[__index1] = __e1;}} Items[__index0] = __e0;}}
        PostInit();
    }

    public static DRDrops DeserializeDRDrops(ByteBuf _buf)
    {
        return new DRDrops(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 掉落 
    /// </summary>
    public readonly int[][] Items;
    public const int __ID__ = -1660362890;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Items:" + Luban.StringUtil.CollectionToString(Items) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
