
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRGameConfig : Luban.BeanBase
{
    public DRGameConfig(ByteBuf _buf) 
    {
        SceneMenu = _buf.ReadInt();
        SceneMain = _buf.ReadInt();
        SceneMap2d = _buf.ReadInt();
        SceneMapFight = _buf.ReadInt();
        PostInit();
    }

    public static DRGameConfig DeserializeDRGameConfig(ByteBuf _buf)
    {
        return new DRGameConfig(_buf);
    }

    public readonly int SceneMenu;
    public readonly int SceneMain;
    public readonly int SceneMap2d;
    public readonly int SceneMapFight;
    public const int __ID__ = 1024952578;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "SceneMenu:" + SceneMenu + ","
        + "SceneMain:" + SceneMain + ","
        + "SceneMap2d:" + SceneMap2d + ","
        + "SceneMapFight:" + SceneMapFight + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
