
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRHero : Luban.BeanBase
{
    public DRHero(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        UnitConfigId = _buf.ReadInt();
        UnitConfigId_Ref = null;
        Name = _buf.ReadString();
        {int __n0 = _buf.ReadSize(); ActiveSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ActiveSkill[__index0] = __e0;}}
        {int __n0 = _buf.ReadSize(); PassiveSkill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); PassiveSkill[__index0] = __e0;}}
        PostInit();
    }

    public static DRHero DeserializeDRHero(ByteBuf _buf)
    {
        return new DRHero(_buf);
    }

    public readonly int Id;
    public readonly int UnitConfigId;
    public DRUnitConfig UnitConfigId_Ref { private set; get; }
    public readonly string Name;
    /// <summary>
    /// 主动技能
    /// </summary>
    public readonly int[] ActiveSkill;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly int[] PassiveSkill;
    public const int __ID__ = 2024756648;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UnitConfigId_Ref = tables.DTUnitConfig.GetOrDefault(UnitConfigId);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UnitConfigId:" + UnitConfigId + ","
        + "Name:" + Name + ","
        + "ActiveSkill:" + Luban.StringUtil.CollectionToString(ActiveSkill) + ","
        + "PassiveSkill:" + Luban.StringUtil.CollectionToString(PassiveSkill) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
