
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRHero : Luban.BeanBase
{
    public DRHero(ByteBuf _buf) 
    {
        Id = _buf.ReadLong();
        UnitConfigId = _buf.ReadInt();
        UnitConfigId_Ref = null;
        Name = _buf.ReadString();
        HeadIcon = _buf.ReadString();
        {int __n0 = _buf.ReadSize(); Skill = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Skill[__index0] = __e0;}}
        BattleCardConfigId = _buf.ReadInt();
        BattleCardConfigId_Ref = null;
        PostInit();
    }

    public static DRHero DeserializeDRHero(ByteBuf _buf)
    {
        return new DRHero(_buf);
    }

    public readonly long Id;
    public readonly int UnitConfigId;
    public DRUnitConfig UnitConfigId_Ref { private set; get; }
    public readonly string Name;
    public readonly string HeadIcon;
    /// <summary>
    /// ActiveSkillIds
    /// </summary>
    public readonly int[] Skill;
    /// <summary>
    /// BattleCardConfigId
    /// </summary>
    public readonly int BattleCardConfigId;
    public DRBattleCardConfig BattleCardConfigId_Ref { private set; get; }
    public const int __ID__ = 2024756648;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UnitConfigId_Ref = tables.DTUnitConfig.GetOrDefault(UnitConfigId);
        BattleCardConfigId_Ref = tables.DTBattleCardConfig.GetOrDefault(BattleCardConfigId);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "UnitConfigId:" + UnitConfigId + ","
        + "Name:" + Name + ","
        + "HeadIcon:" + HeadIcon + ","
        + "Skill:" + Luban.StringUtil.CollectionToString(Skill) + ","
        + "BattleCardConfigId:" + BattleCardConfigId + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
