
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRItems : Luban.BeanBase
{
    public DRItems(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemType = _buf.ReadInt();
        Name = _buf.ReadString();
        Level = _buf.ReadInt();
        Diamond = _buf.ReadInt();
        AreaName = _buf.ReadString();
        Desc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Attr = new System.Collections.Generic.Dictionary<int, long>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { int _k0;  _k0 = _buf.ReadInt(); long _v0;  _v0 = _buf.ReadLong();     Attr.Add(_k0, _v0);}}
        PostInit();
    }

    public static DRItems DeserializeDRItems(ByteBuf _buf)
    {
        return new DRItems(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int ItemType;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品阶
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 价值
    /// </summary>
    public readonly int Diamond;
    /// <summary>
    /// 生长区域
    /// </summary>
    public readonly string AreaName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, long> Attr;
    public const int __ID__ = -1655695406;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ItemType:" + ItemType + ","
        + "Name:" + Name + ","
        + "Level:" + Level + ","
        + "Diamond:" + Diamond + ","
        + "AreaName:" + AreaName + ","
        + "Desc:" + Desc + ","
        + "Attr:" + Luban.StringUtil.CollectionToString(Attr) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
