
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRRelic : Luban.BeanBase
{
    public DRRelic(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        EffectType = _buf.ReadInt();
        EffectValue = _buf.ReadFloat();
        TriggerType = _buf.ReadInt();
        PostInit();
    }

    public static DRRelic DeserializeDRRelic(ByteBuf _buf)
    {
        return new DRRelic(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// Name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Desc
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// EffectType
    /// </summary>
    public readonly int EffectType;
    /// <summary>
    /// EffectValue
    /// </summary>
    public readonly float EffectValue;
    /// <summary>
    /// TriggerType
    /// </summary>
    public readonly int TriggerType;
    public const int __ID__ = -1647823995;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "EffectType:" + EffectType + ","
        + "EffectValue:" + EffectValue + ","
        + "TriggerType:" + TriggerType + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
