
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRSkill : Luban.BeanBase
{
    public DRSkill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Quality = _buf.ReadInt();
        IsAct = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        IconPath = _buf.ReadString();
        CardCopies = _buf.ReadInt();
        CardBaseCostMp = _buf.ReadFloat();
        CardTriggerType = _buf.ReadInt();
        PostInit();
    }

    public static DRSkill DeserializeDRSkill(ByteBuf _buf)
    {
        return new DRSkill(_buf);
    }

    public readonly int Id;
    public readonly int Quality;
    public readonly int IsAct;
    public readonly string Name;
    public readonly string Desc;
    /// <summary>
    /// Icon
    /// </summary>
    public readonly string IconPath;
    /// <summary>
    /// CardCopies
    /// </summary>
    public readonly int CardCopies;
    /// <summary>
    /// BaseMpCost
    /// </summary>
    public readonly float CardBaseCostMp;
    /// <summary>
    /// TriggerType 0Active 1Passive
    /// </summary>
    public readonly int CardTriggerType;
    public const int __ID__ = -1646724509;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Quality:" + Quality + ","
        + "IsAct:" + IsAct + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "IconPath:" + IconPath + ","
        + "CardCopies:" + CardCopies + ","
        + "CardBaseCostMp:" + CardBaseCostMp + ","
        + "CardTriggerType:" + CardTriggerType + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
