
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRSkillCardRule : Luban.BeanBase
{
    public DRSkillCardRule(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DrawCount = _buf.ReadInt();
        HandLimit = _buf.ReadInt();
        CycleSeconds = _buf.ReadFloat();
        MoveDrainMpPerSecond = _buf.ReadFloat();
        PassiveTriggerIntervalSeconds = _buf.ReadFloat();
        PostInit();
    }

    public static DRSkillCardRule DeserializeDRSkillCardRule(ByteBuf _buf)
    {
        return new DRSkillCardRule(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// DrawCount
    /// </summary>
    public readonly int DrawCount;
    /// <summary>
    /// HandLimit
    /// </summary>
    public readonly int HandLimit;
    /// <summary>
    /// CycleSeconds
    /// </summary>
    public readonly float CycleSeconds;
    /// <summary>
    /// MoveDrainMpPerSecond
    /// </summary>
    public readonly float MoveDrainMpPerSecond;
    /// <summary>
    /// PassiveTriggerIntervalSeconds
    /// </summary>
    public readonly float PassiveTriggerIntervalSeconds;
    public const int __ID__ = 1947322799;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DrawCount:" + DrawCount + ","
        + "HandLimit:" + HandLimit + ","
        + "CycleSeconds:" + CycleSeconds + ","
        + "MoveDrainMpPerSecond:" + MoveDrainMpPerSecond + ","
        + "PassiveTriggerIntervalSeconds:" + PassiveTriggerIntervalSeconds + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
