
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRSkillAttribute : Luban.BeanBase
{
    public DRSkillAttribute(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Id_Ref = null;
        Level = _buf.ReadInt();
        Desc = _buf.ReadString();
        CostMana = _buf.ReadInt();
        Attack = _buf.ReadInt();
        PostInit();
    }

    public static DRSkillAttribute DeserializeDRSkillAttribute(ByteBuf _buf)
    {
        return new DRSkillAttribute(_buf);
    }

    public readonly int Id;
    public DRSkill Id_Ref { private set; get; }
    public readonly int Level;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly int CostMana;
    /// <summary>
    /// 属性映射
    /// </summary>
    public readonly int Attack;
    public const int __ID__ = 507563897;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Id_Ref = tables.DTSkill.GetOrDefault(Id);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "Desc:" + Desc + ","
        + "CostMana:" + CostMana + ","
        + "Attack:" + Attack + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
