
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRSkillAttribute : Luban.BeanBase
{
    public DRSkillAttribute(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Id_Ref = null;
        {int n0 = _buf.ReadSize(); Attrs = new System.Collections.Generic.Dictionary<string, int>(n0 * 3 / 2);for(var i0 = 0 ; i0 < n0 ; i0++) { string _k0;  _k0 = _buf.ReadString(); int _v0;  _v0 = _buf.ReadInt();     Attrs.Add(_k0, _v0);}}
        PostInit();
    }

    public static DRSkillAttribute DeserializeDRSkillAttribute(ByteBuf _buf)
    {
        return new DRSkillAttribute(_buf);
    }

    public readonly int Id;
    public DRSkill Id_Ref { private set; get; }
    /// <summary>
    /// AttrMap
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<string, int> Attrs;
    public const int __ID__ = 507563897;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Id_Ref = tables.DTSkill.GetOrDefault(Id);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Attrs:" + Luban.StringUtil.CollectionToString(Attrs) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
