
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRStages : Luban.BeanBase
{
    public DRStages(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
        SubLevel = _buf.ReadInt();
        {int __n0 = _buf.ReadSize(); Monsters = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Monsters[__index0] = __e0;}}
        PostInit();
    }

    public static DRStages DeserializeDRStages(ByteBuf _buf)
    {
        return new DRStages(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 关卡
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 关卡
    /// </summary>
    public readonly int SubLevel;
    /// <summary>
    /// 怪物
    /// </summary>
    public readonly int[] Monsters;
    public const int __ID__ = 499216227;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Level:" + Level + ","
        + "SubLevel:" + SubLevel + ","
        + "Monsters:" + Luban.StringUtil.CollectionToString(Monsters) + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
