
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class DRUnitAttribute : Luban.BeanBase
{
    public DRUnitAttribute(ByteBuf _buf) 
    {
        ConfigId = _buf.ReadInt();
        ConfigId_Ref = null;
        Level = _buf.ReadInt();
        HP = _buf.ReadFloat();
        CriticalProbability = _buf.ReadFloat();
        Mode = _buf.ReadFloat();
        MP = _buf.ReadFloat();
        Attack = _buf.ReadFloat();
        Armor = _buf.ReadFloat();
        MoveSpeed = _buf.ReadLong();
        AttackSpeed = _buf.ReadLong();
        PostInit();
    }

    public static DRUnitAttribute DeserializeDRUnitAttribute(ByteBuf _buf)
    {
        return new DRUnitAttribute(_buf);
    }

    /// <summary>
    /// Mode
    /// </summary>
    public readonly int ConfigId;
    public DRUnitConfig ConfigId_Ref { private set; get; }
    public readonly int Level;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float HP;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CriticalProbability;
    /// <summary>
    /// 心情
    /// </summary>
    public readonly float Mode;
    /// <summary>
    /// 魔法值
    /// </summary>
    public readonly float MP;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly float Attack;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly float Armor;
    /// <summary>
    /// 移速
    /// </summary>
    public readonly long MoveSpeed;
    /// <summary>
    /// 攻击速度
    /// </summary>
    public readonly long AttackSpeed;
    public const int __ID__ = -227056758;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        ConfigId_Ref = tables.DTUnitConfig.GetOrDefault(ConfigId);
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "ConfigId:" + ConfigId + ","
        + "Level:" + Level + ","
        + "HP:" + HP + ","
        + "CriticalProbability:" + CriticalProbability + ","
        + "Mode:" + Mode + ","
        + "MP:" + MP + ","
        + "Attack:" + Attack + ","
        + "Armor:" + Armor + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "AttackSpeed:" + AttackSpeed + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
