
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTDrops : IDataTable
{
    private System.Collections.Generic.Dictionary<int, DRDrops> _dataMap;
    private System.Collections.Generic.List<DRDrops> _dataList;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTDrops(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if(_dataMap == null)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, DRDrops>(n);
            _dataList = new System.Collections.Generic.List<DRDrops>(n);
        }
        else
        {
            _dataMap.Clear();
            _dataList.Clear();
        }
        for(int i = n ; i > 0 ; --i)
        {
            DRDrops _v;
            _v = global::ET.DRDrops.DeserializeDRDrops(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, DRDrops> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<DRDrops> DataList => _dataList;
    public DRDrops GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DRDrops Get(int key) => _dataMap[key];
    public DRDrops this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }


    partial void PostInit();
    partial void PostResolveRef();
}
}
