
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTGameConfig : IDataTable
{

    private DRGameConfig _data;
    public DRGameConfig Data => _data;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTGameConfig(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::ET.DRGameConfig.DeserializeDRGameConfig(_buf);
        PostInit();
    }

    public int SceneMenu => _data.SceneMenu;
    public int SceneMain => _data.SceneMain;
    public int SceneMap2d => _data.SceneMap2d;
    public int SceneMapFight => _data.SceneMapFight;

    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
        PostResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
