
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTSkillAttribute : IDataTable
{
    private System.Collections.Generic.List<DRSkillAttribute> _dataList;
    private System.Collections.Generic.Dictionary<(int, int), DRSkillAttribute> _dataMapUnion;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTSkillAttribute(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if(_dataList == null)
        {
            _dataList = new System.Collections.Generic.List<DRSkillAttribute>(n);
        }
        else
        {
            _dataList.Clear();
        }
        for(int i = n ; i > 0 ; --i)
        {
            DRSkillAttribute _v;
            _v = global::ET.DRSkillAttribute.DeserializeDRSkillAttribute(_buf);
            _dataList.Add(_v);
        }
        if(_dataMapUnion == null)
        {
            _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), DRSkillAttribute>(n);
        }
        else
        {
            _dataMapUnion.Clear();
        }
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Id, _v.Level), _v);
        }
        PostInit();
    }

    public System.Collections.Generic.IReadOnlyList<DRSkillAttribute> DataList => _dataList;
    public DRSkillAttribute Get(int Id, int Level) => _dataMapUnion.TryGetValue((Id, Level), out DRSkillAttribute __v) ? __v : default;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
