
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class DTUnitAttribute : IDataTable
{
    private System.Collections.Generic.List<DRUnitAttribute> _dataList;
    private System.Collections.Generic.Dictionary<(int, int, int), DRUnitAttribute> _dataMapUnion;
    private readonly System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> _loadFunc;

    public DTUnitAttribute(System.Func<Cysharp.Threading.Tasks.UniTask<ByteBuf>> loadFunc)
    {
        _loadFunc = loadFunc;
    }

    public async Cysharp.Threading.Tasks.UniTask LoadAsync()
    {
        ByteBuf _buf = await _loadFunc();
        int n = _buf.ReadSize();
        if(_dataList == null)
        {
            _dataList = new System.Collections.Generic.List<DRUnitAttribute>(n);
        }
        else
        {
            _dataList.Clear();
        }
        for(int i = n ; i > 0 ; --i)
        {
            DRUnitAttribute _v;
            _v = global::ET.DRUnitAttribute.DeserializeDRUnitAttribute(_buf);
            _dataList.Add(_v);
        }
        if(_dataMapUnion == null)
        {
            _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int, int), DRUnitAttribute>(n);
        }
        else
        {
            _dataMapUnion.Clear();
        }
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.ConfigId, _v.Level, _v.SubLevel), _v);
        }
        PostInit();
    }

    public System.Collections.Generic.IReadOnlyList<DRUnitAttribute> DataList => _dataList;
    public DRUnitAttribute Get(int ConfigId, int Level, int SubLevel) => _dataMapUnion.TryGetValue((ConfigId, Level, SubLevel), out DRUnitAttribute __v) ? __v : default;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
        PostResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
