
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class Int3 : Luban.BeanBase
{
    public Int3(ByteBuf _buf) 
    {
        Item1 = _buf.ReadInt();
        Item2 = _buf.ReadInt();
        Item3 = _buf.ReadInt();
        PostInit();
    }

    public static Int3 DeserializeInt3(ByteBuf _buf)
    {
        return new Int3(_buf);
    }

    public readonly int Item1;
    public readonly int Item2;
    public readonly int Item3;
    public const int __ID__ = 2284100;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "Item1:" + Item1 + ","
        + "Item2:" + Item2 + ","
        + "Item3:" + Item3 + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
