
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class Tables
{
    public DTScene DTScene { private set; get; }
    public DTMusic DTMusic { private set; get; }
    public DTOneConfig DTOneConfig { private set; get; }
    public DTAIConfig DTAIConfig { private set; get; }
    public DTUnitConfig DTUnitConfig { private set; get; }
    public DTUnitAttribute DTUnitAttribute { private set; get; }
    public DTGenAtom DTGenAtom { private set; get; }
    public DTSkill DTSkill { private set; get; }
    public DTSkillGraph DTSkillGraph { private set; get; }
    public DTHero DTHero { private set; get; }
    public DTMonster DTMonster { private set; get; }
    public DTGameAI DTGameAI { private set; get; }
    public DTSkillCardRule DTSkillCardRule { private set; get; }
    public DTBattleCardConfig DTBattleCardConfig { private set; get; }
    public DTRelic DTRelic { private set; get; }
    public DTSkillAttribute DTSkillAttribute { private set; get; }
    public DTGameConfig DTGameConfig { private set; get; }
    public DTItems DTItems { private set; get; }
    public DTStages DTStages { private set; get; }
    private System.Collections.Generic.Dictionary<string, IDataTable> _tables;
    public System.Collections.Generic.IEnumerable<IDataTable> DataTables => _tables.Values;
    public IDataTable GetDataTable(string tableName) => _tables.TryGetValue(tableName, out var v) ? v : null;

    public async Cysharp.Threading.Tasks.UniTask LoadAsync(System.Func<string, Cysharp.Threading.Tasks.UniTask<ByteBuf>> loader)
    {
        TablesMemory.BeginRecord();

        _tables = new System.Collections.Generic.Dictionary<string, IDataTable>();
        var loadTasks = new System.Collections.Generic.List<Cysharp.Threading.Tasks.UniTask>();

        DTScene = new DTScene(() => loader("dtscene"));
        loadTasks.Add(DTScene.LoadAsync());
        _tables.Add("DTScene", DTScene);
        DTMusic = new DTMusic(() => loader("dtmusic"));
        loadTasks.Add(DTMusic.LoadAsync());
        _tables.Add("DTMusic", DTMusic);
        DTOneConfig = new DTOneConfig(() => loader("dtoneconfig"));
        loadTasks.Add(DTOneConfig.LoadAsync());
        _tables.Add("DTOneConfig", DTOneConfig);
        DTAIConfig = new DTAIConfig(() => loader("dtaiconfig"));
        loadTasks.Add(DTAIConfig.LoadAsync());
        _tables.Add("DTAIConfig", DTAIConfig);
        DTUnitConfig = new DTUnitConfig(() => loader("dtunitconfig"));
        loadTasks.Add(DTUnitConfig.LoadAsync());
        _tables.Add("DTUnitConfig", DTUnitConfig);
        DTUnitAttribute = new DTUnitAttribute(() => loader("dtunitattribute"));
        loadTasks.Add(DTUnitAttribute.LoadAsync());
        _tables.Add("DTUnitAttribute", DTUnitAttribute);
        DTGenAtom = new DTGenAtom(() => loader("dtgenatom"));
        loadTasks.Add(DTGenAtom.LoadAsync());
        _tables.Add("DTGenAtom", DTGenAtom);
        DTSkill = new DTSkill(() => loader("dtskill"));
        loadTasks.Add(DTSkill.LoadAsync());
        _tables.Add("DTSkill", DTSkill);
        DTSkillGraph = new DTSkillGraph(() => loader("dtskillgraph"));
        loadTasks.Add(DTSkillGraph.LoadAsync());
        _tables.Add("DTSkillGraph", DTSkillGraph);
        DTHero = new DTHero(() => loader("dthero"));
        loadTasks.Add(DTHero.LoadAsync());
        _tables.Add("DTHero", DTHero);
        DTMonster = new DTMonster(() => loader("dtmonster"));
        loadTasks.Add(DTMonster.LoadAsync());
        _tables.Add("DTMonster", DTMonster);
        DTGameAI = new DTGameAI(() => loader("dtgameai"));
        loadTasks.Add(DTGameAI.LoadAsync());
        _tables.Add("DTGameAI", DTGameAI);
        DTSkillCardRule = new DTSkillCardRule(() => loader("dtskillcardrule"));
        loadTasks.Add(DTSkillCardRule.LoadAsync());
        _tables.Add("DTSkillCardRule", DTSkillCardRule);
        DTBattleCardConfig = new DTBattleCardConfig(() => loader("dtbattlecardconfig"));
        loadTasks.Add(DTBattleCardConfig.LoadAsync());
        _tables.Add("DTBattleCardConfig", DTBattleCardConfig);
        DTRelic = new DTRelic(() => loader("dtrelic"));
        loadTasks.Add(DTRelic.LoadAsync());
        _tables.Add("DTRelic", DTRelic);
        DTSkillAttribute = new DTSkillAttribute(() => loader("dtskillattribute"));
        loadTasks.Add(DTSkillAttribute.LoadAsync());
        _tables.Add("DTSkillAttribute", DTSkillAttribute);
        DTGameConfig = new DTGameConfig(() => loader("dtgameconfig"));
        loadTasks.Add(DTGameConfig.LoadAsync());
        _tables.Add("DTGameConfig", DTGameConfig);
        DTItems = new DTItems(() => loader("dtitems"));
        loadTasks.Add(DTItems.LoadAsync());
        _tables.Add("DTItems", DTItems);
        DTStages = new DTStages(() => loader("dtstages"));
        loadTasks.Add(DTStages.LoadAsync());
        _tables.Add("DTStages", DTStages);

        await Cysharp.Threading.Tasks.UniTask.WhenAll(loadTasks);

        Refresh();

        TablesMemory.EndRecord();
    }

    private void ResolveRef()
    {
        DTScene.ResolveRef(this);
        DTMusic.ResolveRef(this);
        DTOneConfig.ResolveRef(this);
        DTAIConfig.ResolveRef(this);
        DTUnitConfig.ResolveRef(this);
        DTUnitAttribute.ResolveRef(this);
        DTGenAtom.ResolveRef(this);
        DTSkill.ResolveRef(this);
        DTSkillGraph.ResolveRef(this);
        DTHero.ResolveRef(this);
        DTMonster.ResolveRef(this);
        DTGameAI.ResolveRef(this);
        DTSkillCardRule.ResolveRef(this);
        DTBattleCardConfig.ResolveRef(this);
        DTRelic.ResolveRef(this);
        DTSkillAttribute.ResolveRef(this);
        DTGameConfig.ResolveRef(this);
        DTItems.ResolveRef(this);
        DTStages.ResolveRef(this);
        PostResolveRef();
    }

    public void Refresh()
    {
        PostInit();
        ResolveRef();
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
