
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public sealed partial class Vector2Int : Luban.BeanBase
{
    public Vector2Int(ByteBuf _buf) 
    {
        X = _buf.ReadInt();
        Y = _buf.ReadInt();
        PostInit();
    }

    public static Vector2Int DeserializeVector2Int(ByteBuf _buf)
    {
        return new Vector2Int(_buf);
    }

    public readonly int X;
    public readonly int Y;
    public const int __ID__ = 2010857024;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "x:" + X + ","
        + "y:" + Y + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
