
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    /// <summary>
    /// Five element root flags
    /// </summary>
    [System.Flags]
    public enum XRoot
    {
        /// <summary>
        /// Gold
        /// </summary>
        Gold = 1,
        /// <summary>
        /// Wood
        /// </summary>
        Wood = 2,
        /// <summary>
        /// Water
        /// </summary>
        Water = 4,
        /// <summary>
        /// Fire
        /// </summary>
        Fire = 8,
        /// <summary>
        /// Ground
        /// </summary>
        Ground = 16,
    }

} 

