// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoGFEntityDropItem
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.SpriteRenderer m_HeadSpriteRenderer;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.Transform m_RootTransform;


        public UnityEngine.SpriteRenderer HeadSpriteRenderer => m_HeadSpriteRenderer;
        public UnityEngine.Transform RootTransform => m_RootTransform;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_HeadSpriteRenderer == null) return true;
            if (this.m_RootTransform == null) return true;
            return false;
        }
#endif
    }
}
