// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormShop
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIWidgetBtmBar m_BtmBarBtmBar;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_BuyExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExLoopVerticalScrollRect m_ShopLoopVerticalScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggle m_ShopTab0UXToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggle m_ShopTab1UXToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggle m_ShopTab2UXToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggleGroup m_ShopTabsUXToggleGroup;

        public ET.Client.MonoUIWidgetBtmBar BtmBarBtmBar => this.m_BtmBarBtmBar;
        public Game.ExButton BuyExButton => this.m_BuyExButton;
        public Game.ExLoopVerticalScrollRect ShopLoopVerticalScrollRect => this.m_ShopLoopVerticalScrollRect;
        public UnityEngine.UI.UXToggle ShopTab0UXToggle => this.m_ShopTab0UXToggle;
        public UnityEngine.UI.UXToggle ShopTab1UXToggle => this.m_ShopTab1UXToggle;
        public UnityEngine.UI.UXToggle ShopTab2UXToggle => this.m_ShopTab2UXToggle;
        public UnityEngine.UI.UXToggleGroup ShopTabsUXToggleGroup => this.m_ShopTabsUXToggleGroup;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_BtmBarBtmBar == null) return true;
            if (this.m_BuyExButton == null) return true;
            if (this.m_ShopLoopVerticalScrollRect == null) return true;
            if (this.m_ShopTab0UXToggle == null) return true;
            if (this.m_ShopTab1UXToggle == null) return true;
            if (this.m_ShopTab2UXToggle == null) return true;
            if (this.m_ShopTabsUXToggleGroup == null) return true;
            return false;
        }
#endif

    }
}
