// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIShopItem
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_CountUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_IconImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_NameUXTextMeshPro;

        public UnityEngine.UI.UXTextMeshPro CountUXTextMeshPro => this.m_CountUXTextMeshPro;
        public UnityEngine.UI.Image IconImage => this.m_IconImage;
        public UnityEngine.UI.UXTextMeshPro NameUXTextMeshPro => this.m_NameUXTextMeshPro;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_CountUXTextMeshPro == null) return true;
            if (this.m_IconImage == null) return true;
            if (this.m_NameUXTextMeshPro == null) return true;
            return false;
        }
#endif

    }
}
