// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormShop
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIWidgetBtmBar m_BtmBarBtmBar;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.CommonLoopScrollRect m_ShopCommonLoopScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggle m_ShopTab0UXToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggle m_ShopTab1UXToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggle m_ShopTab2UXToggle;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXToggleGroup m_ShopTabsUXToggleGroup;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_ShopTempExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_ShopTempImage;


        public ET.Client.MonoUIWidgetBtmBar BtmBarBtmBar => m_BtmBarBtmBar;
        public Game.CommonLoopScrollRect ShopCommonLoopScrollRect => m_ShopCommonLoopScrollRect;
        public UnityEngine.UI.UXToggle ShopTab0UXToggle => m_ShopTab0UXToggle;
        public UnityEngine.UI.UXToggle ShopTab1UXToggle => m_ShopTab1UXToggle;
        public UnityEngine.UI.UXToggle ShopTab2UXToggle => m_ShopTab2UXToggle;
        public UnityEngine.UI.UXToggleGroup ShopTabsUXToggleGroup => m_ShopTabsUXToggleGroup;
        public Game.ExButton ShopTempExButton => m_ShopTempExButton;
        public UnityEngine.UI.Image ShopTempImage => m_ShopTempImage;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_BtmBarBtmBar == null) return true;
            if (this.m_ShopCommonLoopScrollRect == null) return true;
            if (this.m_ShopTab0UXToggle == null) return true;
            if (this.m_ShopTab1UXToggle == null) return true;
            if (this.m_ShopTab2UXToggle == null) return true;
            if (this.m_ShopTabsUXToggleGroup == null) return true;
            if (this.m_ShopTempExButton == null) return true;
            if (this.m_ShopTempImage == null) return true;
            return false;
        }
#endif
    }
}
