// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUISkillsItem
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_ClickExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_EquippedImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_IconImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_LevelTextMeshProUGUI;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private TMPro.TextMeshProUGUI m_NameTextMeshProUGUI;


        public Game.ExButton ClickExButton => m_ClickExButton;
        public UnityEngine.UI.Image EquippedImage => m_EquippedImage;
        public UnityEngine.UI.Image IconImage => m_IconImage;
        public TMPro.TextMeshProUGUI LevelTextMeshProUGUI => m_LevelTextMeshProUGUI;
        public TMPro.TextMeshProUGUI NameTextMeshProUGUI => m_NameTextMeshProUGUI;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_ClickExButton == null) return true;
            if (this.m_EquippedImage == null) return true;
            if (this.m_IconImage == null) return true;
            if (this.m_LevelTextMeshProUGUI == null) return true;
            if (this.m_NameTextMeshProUGUI == null) return true;
            return false;
        }
#endif
    }
}
