// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormSkills
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private ET.Client.MonoUIWidgetBtmBar m_BtmBarBtmBar;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_LevelUpExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExLoopHorizontalScrollRect m_Skill0LoopHorizontalScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExLoopHorizontalScrollRect m_Skill1LoopHorizontalScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Slider m_SkillExpSlider;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_SkillExpTxtUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_SkillLevelUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.UXTextMeshPro m_SkillNameUXTextMeshPro;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_SkillTemp1ExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_SkillTemp1Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_SkillTemp2ExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_SkillTemp2Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_SkillTemp3ExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_SkillTemp3Image;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("Binding Targets"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExLoopVerticalScrollRect m_SkillsLoopVerticalScrollRect;

        public ET.Client.MonoUIWidgetBtmBar BtmBarBtmBar => this.m_BtmBarBtmBar;
        public Game.ExButton LevelUpExButton => this.m_LevelUpExButton;
        public Game.ExLoopHorizontalScrollRect Skill0LoopHorizontalScrollRect => this.m_Skill0LoopHorizontalScrollRect;
        public Game.ExLoopHorizontalScrollRect Skill1LoopHorizontalScrollRect => this.m_Skill1LoopHorizontalScrollRect;
        public UnityEngine.UI.Slider SkillExpSlider => this.m_SkillExpSlider;
        public UnityEngine.UI.UXTextMeshPro SkillExpTxtUXTextMeshPro => this.m_SkillExpTxtUXTextMeshPro;
        public UnityEngine.UI.UXTextMeshPro SkillLevelUXTextMeshPro => this.m_SkillLevelUXTextMeshPro;
        public UnityEngine.UI.UXTextMeshPro SkillNameUXTextMeshPro => this.m_SkillNameUXTextMeshPro;
        public Game.ExButton SkillTemp1ExButton => this.m_SkillTemp1ExButton;
        public UnityEngine.UI.Image SkillTemp1Image => this.m_SkillTemp1Image;
        public Game.ExButton SkillTemp2ExButton => this.m_SkillTemp2ExButton;
        public UnityEngine.UI.Image SkillTemp2Image => this.m_SkillTemp2Image;
        public Game.ExButton SkillTemp3ExButton => this.m_SkillTemp3ExButton;
        public UnityEngine.UI.Image SkillTemp3Image => this.m_SkillTemp3Image;
        public Game.ExLoopVerticalScrollRect SkillsLoopVerticalScrollRect => this.m_SkillsLoopVerticalScrollRect;

#if UNITY_EDITOR
        [Sirenix.OdinInspector.OnInspectorGUI, Sirenix.OdinInspector.PropertyOrder(-99999), Sirenix.OdinInspector.ShowIf(nameof(HasMissingTargets))]
        private void DrawMissingTargetsWarning()
        {
            Sirenix.Utilities.Editor.SirenixEditorGUI.MessageBox("Binding targets contain missing references.", UnityEditor.MessageType.Warning);
        }

        private bool HasMissingTargets()
        {
            if (this.m_BtmBarBtmBar == null) return true;
            if (this.m_LevelUpExButton == null) return true;
            if (this.m_Skill0LoopHorizontalScrollRect == null) return true;
            if (this.m_Skill1LoopHorizontalScrollRect == null) return true;
            if (this.m_SkillExpSlider == null) return true;
            if (this.m_SkillExpTxtUXTextMeshPro == null) return true;
            if (this.m_SkillLevelUXTextMeshPro == null) return true;
            if (this.m_SkillNameUXTextMeshPro == null) return true;
            if (this.m_SkillTemp1ExButton == null) return true;
            if (this.m_SkillTemp1Image == null) return true;
            if (this.m_SkillTemp2ExButton == null) return true;
            if (this.m_SkillTemp2Image == null) return true;
            if (this.m_SkillTemp3ExButton == null) return true;
            if (this.m_SkillTemp3Image == null) return true;
            if (this.m_SkillsLoopVerticalScrollRect == null) return true;
            return false;
        }
#endif

    }
}
