// This is automatically generated by CodeBind. Please do not modify it.

namespace ET.Client
{
    public partial class MonoUIFormSkills
    {
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_ReturnExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.CommonLoopScrollRect m_Skill0CommonLoopScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.CommonLoopScrollRect m_Skill1CommonLoopScrollRect;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Slider m_SkillExpSlider;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.ExButton m_SkillTempExButton;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private UnityEngine.UI.Image m_SkillTempImage;
        [UnityEngine.SerializeField, Sirenix.OdinInspector.FoldoutGroup("BindData"), Sirenix.OdinInspector.ReadOnly]
        private Game.CommonLoopScrollRect m_SkillsCommonLoopScrollRect;


        public Game.ExButton ReturnExButton => m_ReturnExButton;
        public Game.CommonLoopScrollRect Skill0CommonLoopScrollRect => m_Skill0CommonLoopScrollRect;
        public Game.CommonLoopScrollRect Skill1CommonLoopScrollRect => m_Skill1CommonLoopScrollRect;
        public UnityEngine.UI.Slider SkillExpSlider => m_SkillExpSlider;
        public Game.ExButton SkillTempExButton => m_SkillTempExButton;
        public UnityEngine.UI.Image SkillTempImage => m_SkillTempImage;
        public Game.CommonLoopScrollRect SkillsCommonLoopScrollRect => m_SkillsCommonLoopScrollRect;


#if UNITY_EDITOR
        [Sirenix.OdinInspector.HideLabel, Sirenix.OdinInspector.ReadOnly, Sirenix.OdinInspector.ShowInInspector]
        [Sirenix.OdinInspector.GUIColor(1f, 0.8f, 0f), Sirenix.OdinInspector.PropertyOrder(-99999)]
        [Sirenix.OdinInspector.ShowIf(nameof(CheckBindDataExitEmpty))]
        private string BindDataExitEmptyWarning => "BindData contains empty reference, please check.";

        private bool CheckBindDataExitEmpty()
        {
            if (this.m_ReturnExButton == null) return true;
            if (this.m_Skill0CommonLoopScrollRect == null) return true;
            if (this.m_Skill1CommonLoopScrollRect == null) return true;
            if (this.m_SkillExpSlider == null) return true;
            if (this.m_SkillTempExButton == null) return true;
            if (this.m_SkillTempImage == null) return true;
            if (this.m_SkillsCommonLoopScrollRect == null) return true;
            return false;
        }
#endif
    }
}
